site_name: Addon Encyclopedia 
site_url: https://fanglimao.github.io/addon-encyclopedia
copyright: 如无特殊说明，本网站内容采用 CC BY-NC-SA 4.0 协议进行许可

nav:
  - 主页: index.md
  - 教程:
    - 附加包入门:
      - 什么是附加包: tutorial/start.md
      - 认识JSON: tutorial/json.md
      - 启动项目: tutorial/first-addon.md  
      - 自定义物品: tutorial/add-custom-item.md
      - 自定义方块: tutorial/add-custom-block.md
      - 添加配方: tutorial/add-recipe.md
      - 自定义实体: tutorial/add-custom-entity.md
      - 脚本初步: tutorial/script.md
  - 物品:
    - 简介: item/index.md
    - 描述: item/description.md
    - 标签: item/tags.md
  - 方块:
    - 标签: block/tags.md
  - 配方:
    - 简介: recipe/index.md
    - 标签: recipe/tags.md
    - 配方解锁: recipe/unlock.md
  - 脚本:
    - 自定义组件: script/custom-components.md
  - 工具与资源: 
    - 开源脚本库: resource/script-lib.md
    - 编辑器:
      - 编辑器概述: resource/editor/overview.md
      - 用户界面: resource/editor/ui.md
      - 延迟渲染: resource/editor/deferred-lighting.md
    - 资源:
      - 原版附加包: resource/vanilla-pack.md
    - 在线工具:
      - UUID生成器: resource/uuid.md
      - 方块渲染器: resource/block-renderer.md
    - 代码编辑器:
      - Bridge.: resource/bridge.md
      - VS Code: resource/vsc.md
      - MT管理器: resource/mt.md
  - 参考文档: 
    - 格式化代码: reference/format-code.md   
    - 数据驱动:
      - 内容文件: reference/data-driven/contents.md
    - 方块组件: 
      - breathability: reference/block/components/breathability.md
      - collision_box: reference/block/components/collision_box.md
    - 物品组件:
      - allow_off_hand: reference/item/components/allow_off_hand.md
      - block_placer: reference/item/components/block_placer.md
      - bundle_interaction: reference/item/components/bundle_interaction.md
      - can_destroy_in_creative: reference/item/components/can_destroy_in_creative.md
      - cooldown: reference/item/components/cooldown.md
      - damage: reference/item/components/damage.md
      - digger: reference/item/components/digger.md
      - display_name: reference/item/components/display_name.md
      - durability: reference/item/components/durability.md
      - enchantable: reference/item/components/enchantable.md
      - entity_placer: reference/item/components/entity_placer.md
      - food: reference/item/components/food.md
      - fuel: reference/item/components/fuel.md
      - glint: reference/item/components/glint.md
      - hand_equipped: reference/item/components/hand_equipped.md
      - hover_text_color: reference/item/components/hover_text_color.md
      - icon: reference/item/components/icon.md
      - interact_button: reference/item/components/interact_button.md
      - liquid_clipped: reference/item/components/liquid_clipped.md
      - max_stack_size: reference/item/components/max_stack_size.md
      - projectile: reference/item/components/projectile.md
      - rarity: reference/item/components/rarity.md
      - record: reference/item/components/record.md
      - repairable: reference/item/components/repairable.md
      - shooter: reference/item/components/shooter.md
      - should_despawn: reference/item/components/should_despawn.md
      - stacked_by_data: reference/item/components/stacked_by_data.md
      - tags: reference/item/components/tags.md
      - throwable: reference/item/components/throwable.md
      - use_animation: reference/item/components/use_animation.md
      - use_modifiers: reference/item/components/use_modifiers.md
      - wearable: reference/item/components/wearable.md
plugins:
  - search
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - footnotes
  - md_in_html  
  - abbr
  - pymdownx.snippets
theme:
  name: material
  language: zh 
  logo: assets/bedrock.png
  favicon: assets/bedrock.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer 
    - header.autohide  
    - navigation.tabs 
    - navigation.tabs.sticky 
    - navigation.top
    - toc.integrate
    - navigation.expand
    - navigation.sections  
    - content.tooltips              
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: 切换至深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换至浅色模式